name: AMGMA CI

on: [push, pull_request]  

jobs:

  workflow:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name:  Build Database
        working-directory: /tmp/
        run: |
          NXF_VER=19.10.0 nextflow run build_db.nf -with-docker ubuntu:18.04 -w work/ --manifest data/genome.manifest.csv --output_folder db --output_prefix amgma -profile testing
        - name:  Align Results
        working-directory: /tmp/
        run: |
        NXF_VER=19.10.0 nextflow run align.nf -with-docker ubuntu:18.04 -w work/ --geneshot_hdf data/geneshot.summary.hdf5 --geneshot_fasta data/genes.fasta.gz --db_dmnd db/amgma_test.dmnd --db_hdf db/amgma_test.hdf --output_folder output --output_hdf amgma_test.output.hdf -profile testing 
