name: AMGMA CI

on: [push, pull_request]  

jobs:

  align:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name:  Align Results
        run: |
          cd $GITHUB_WORKSPACE && NXF_VER=20.01.0 nextflow run align.nf -with-docker ubuntu:18.04 -w work/ --geneshot_hdf data/geneshot.summary.hdf5 --geneshot_dmnd data/geneshot.dmnd --db_dmnd data/amgma.dmnd --db_hdf data/amgma.hdf --output_folder output --output_hdf amgma_test.output.hdf -profile testing 
        working-directory: /tmp/

  buildDB:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name:  Build Database
        run: |
          cd $GITHUB_WORKSPACE && NXF_VER=20.01.0 nextflow run build_db.nf -with-docker ubuntu:18.04 -w work/ --manifest data/genome.manifest.csv --output_folder db --output_prefix amgma -profile testing --batchsize 2 
        working-directory: /tmp/

  workflow:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name:  Build Database
        run: |
          cd $GITHUB_WORKSPACE && NXF_VER=20.01.0 nextflow run build_db.nf -with-docker ubuntu:18.04 -w work/ --manifest data/genome.manifest.csv --output_folder db --output_prefix amgma -profile testing --batchsize 2 
        working-directory: /tmp/
      - name:  Align Results
        run: |
          cd $GITHUB_WORKSPACE && NXF_VER=20.01.0 nextflow run align.nf -with-docker ubuntu:18.04 -w work/ --geneshot_hdf data/geneshot.summary.hdf5 --geneshot_dmnd data/geneshot.dmnd --db_dmnd db/amgma.dmnd --db_hdf db/amgma.hdf --output_folder output --output_hdf amgma_test.output.hdf -profile testing 
        working-directory: /tmp/
